import test from 'node:test';
import assert from 'node:assert/strict';
import { createCallLifecycle } from './lifecycle.mjs';
const deferred = () => { let resolve, reject; const promise = new Promise((a,b) => { resolve=a; reject=b; }); return {promise,resolve,reject}; };
const flush = async () => { for(let i=0;i<24;i++) await Promise.resolve(); };
function track() { const t=new EventTarget(); return Object.assign(t,{kind:'audio',enabled:true,readyState:'live',stops:0,stop(){this.enabled=false;this.readyState='ended';this.stops++;}}); }
const stream = tracks => ({getTracks:()=>tracks});
function fixture(overrides={}) {
 const log=[], made=[], stages=[];
 const port={ authorize:async()=>Object.freeze({opaque:'fixture-only-not-authority'}), acquire:async()=>{const t=track();made.push(t);return stream([t]);},
  join:async()=>session, prepare:async args=>{assert.ok(args.tracks.every(t=>!t.enabled));const s={disposed:0,commits:0,async commit(){this.commits++;assert.ok(args.tracks.every(t=>!t.enabled));},dispose(){this.disposed++;}};stages.push(s);return s;},...overrides};
 const session={closed:0,close(){this.closed++;},preparePublication:args=>{log.push('prepare');return port.prepare(args);}};
 const app=createCallLifecycle({host:{authorize:(...args)=>{log.push('authorize:'+args[1]);return port.authorize(...args);}},media:{acquire:args=>{log.push('acquire');return port.acquire(args);}},transport:{join:args=>{log.push('join');return port.join(args);}},onState:overrides.onState});
 app.setIdentity({accountId:'A',deviceId:'D'});
 return {app,port,session,log,made,stages,join:()=>app.join({roomId:'R',mode:'group'})};
}
test('join listens mic OFF, no permission or optional extras; explicit mic enable only',async()=>{const f=fixture();assert.deepEqual(await f.join(),{ok:true});assert.equal(f.app.snapshot().state,'listening');assert.equal(f.app.snapshot().microphone,'off');assert.deepEqual(f.log,['authorize:join','join']);await f.app.enableMicrophone();assert.equal(f.app.snapshot().microphone,'on');assert.equal(f.made[0].enabled,true);f.app.end();});
test('repeated pending join/mic intents coalesce exactly',async()=>{const j=deferred(),m=deferred(),f=fixture({join:()=>j.promise,acquire:()=>m.promise});const a=f.join(),b=f.join();assert.equal(a,b);await flush();assert.equal(f.log.filter(x=>x==='join').length,1);j.resolve(f.session);await a;const c=f.app.enableMicrophone(),d=f.app.enableMicrophone();assert.equal(c,d);await flush();assert.equal(f.log.filter(x=>x==='acquire').length,1);m.resolve(stream([track()]));await c;f.app.end();});
test('different room cannot silently replace current call',async()=>{const f=fixture();await f.join();assert.deepEqual(await f.app.join({roomId:'other',mode:'one-to-one'}),{ok:false,code:'call_active'});assert.equal(f.session.closed,0);f.app.end();});
test('scope is frozen snapshot of identity/device/room/mode/generation',async()=>{let seen;const f=fixture({authorize:async scope=>{seen=scope;return {};}});await f.join();assert.ok(Object.isFrozen(seen));assert.equal(seen.accountId,'A');assert.equal(seen.deviceId,'D');assert.equal(seen.roomId,'R');assert.equal(seen.mode,'group');assert.equal(seen.generation,1);assert.throws(()=>seen.roomId='evil',TypeError);f.app.end();});
test('same account navigation and identity refresh keep active microphone',async()=>{const f=fixture();await f.join();await f.app.enableMicrophone();const scope=f.app.snapshot().scope;f.app.navigate();f.app.setIdentity({accountId:'A',deviceId:'D'});assert.equal(f.app.snapshot().scope,scope);assert.equal(f.made[0].stops,0);f.app.end();});
test('mute stops capture and detaches publication; unmute reacquires',async()=>{const f=fixture();await f.join();await f.app.enableMicrophone();const e=f.app.mute().localEvidence;assert.equal(f.made[0].readyState,'ended');assert.equal(f.stages[0].disposed,1);assert.equal(e.endedLocallyObserved,1);await f.app.enableMicrophone();assert.equal(f.made.length,2);assert.equal(f.made[1].enabled,true);f.app.end();});
for(const action of ['mute','end','cancel','revoke','dispose']) test(action+' fences late permission and stops every late track',async()=>{const p=deferred(),f=fixture({acquire:()=>p.promise});await f.join();const pending=f.app.enableMicrophone();await flush();f.app[action]();assert.equal((await pending).code,'stale');const tracks=[track(),track()];p.resolve(stream(tracks));await flush();assert.ok(tracks.every(t=>t.readyState==='ended'&&!t.enabled));assert.equal(f.log.includes('prepare'),false);assert.equal(f.app.snapshot().localEvidence.endedLocallyObserved,2);});
for(const identity of [{accountId:'B',deviceId:'D'},{accountId:'A',deviceId:'E'},null]) test('identity transition '+JSON.stringify(identity)+' stops active tracks',async()=>{const f=fixture();await f.join();await f.app.enableMicrophone();f.app.setIdentity(identity);assert.equal(f.made[0].readyState,'ended');assert.equal(f.session.closed,1);assert.equal(f.app.snapshot().microphone,'off');});
test('cancel before queued join starts calls no authorization/transport',async()=>{const f=fixture();const p=f.join();f.app.cancel();await p;await flush();assert.deepEqual(f.log,[]);});
test('cancel before queued mic starts calls no permission port',async()=>{const f=fixture();await f.join();const p=f.app.enableMicrophone();f.app.mute();await p;await flush();assert.equal(f.log.includes('acquire'),false);f.app.end();});
test('late joined session closes and cannot revive cancelled call',async()=>{const j=deferred(),f=fixture({join:()=>j.promise});const p=f.join();await flush();f.app.end();assert.equal((await p).code,'stale');j.resolve(f.session);await flush();assert.equal(f.session.closed,1);assert.equal(f.app.snapshot().state,'ended');});
test('ABA stale old join cannot replace latest session',async()=>{const old=deferred(),f=fixture({join:()=>old.promise});const p=f.join();await flush();f.app.setIdentity({accountId:'B',deviceId:'D'});f.app.setIdentity({accountId:'A',deviceId:'D'});const latest={close(){},preparePublication(){}};f.port.join=async()=>latest;await f.join();const scope=f.app.snapshot().scope;old.resolve(f.session);await p;await flush();assert.equal(f.session.closed,1);assert.equal(f.app.snapshot().scope,scope);assert.equal(scope.generation,2);f.app.end();});
test('late old permission cannot stop new same-room capture',async()=>{const old=deferred(),f=fixture({acquire:()=>old.promise});await f.join();const a=f.app.enableMicrophone();await flush();f.app.mute();const fresh=track();f.port.acquire=async()=>stream([fresh]);await f.app.enableMicrophone();const stale=track();old.resolve(stream([stale]));await a;await flush();assert.equal(stale.readyState,'ended');assert.equal(fresh.readyState,'live');assert.equal(fresh.enabled,true);f.app.end();});
test('pending stage with mute stops now, disposes late stage, never commits',async()=>{const p=deferred(),f=fixture({prepare:()=>p.promise});await f.join();const job=f.app.enableMicrophone();await flush();assert.equal(f.made[0].enabled,false);f.app.mute();assert.equal(f.made[0].readyState,'ended');let disposed=0,committed=0;p.resolve({dispose(){disposed++;},commit(){committed++;}});await job;await flush();assert.equal(disposed,1);assert.equal(committed,0);f.app.end();});
test('end during commit stops now; late commit completion never enables',async()=>{const p=deferred();let disposed=0;const f=fixture({prepare:async()=>({dispose(){disposed++;},commit:()=>p.promise})});await f.join();const job=f.app.enableMicrophone();await flush();assert.equal(f.made[0].enabled,false);f.app.end();assert.equal(f.made[0].readyState,'ended');p.resolve();await job;await flush();assert.equal(f.made[0].enabled,false);assert.equal(disposed,1);});
test('native ended event retires all local capture/publication',async()=>{const tracks=[track(),track()],f=fixture({acquire:async()=>stream(tracks)});await f.join();await f.app.enableMicrophone();tracks[0].readyState='ended';tracks[0].dispatchEvent(new Event('ended'));assert.equal(f.app.snapshot().microphone,'off');assert.equal(f.app.snapshot().code,'microphone_ended');assert.equal(tracks[1].readyState,'ended');assert.equal(f.stages[0].disposed,1);f.app.end();});
test('track ending without event during commit cannot produce on state',async()=>{const p=deferred(),f=fixture({prepare:async()=>({dispose(){},commit:()=>p.promise})});await f.join();const job=f.app.enableMicrophone();await flush();f.made[0].readyState='ended';p.resolve();assert.equal((await job).code,'microphone_failed');assert.equal(f.app.snapshot().microphone,'off');f.app.end();});
test('permission/transport private errors are never read or exposed',async()=>{let reads=0;const secret=new Proxy({}, {get(){reads++;throw Error('no');}});const f=fixture({authorize:async()=>{throw secret;}});assert.deepEqual(await f.join(),{ok:false,code:'join_failed'});assert.equal(reads,0);assert.equal(f.app.snapshot().code,'join_failed');});
test('boolean admission is not accepted as an authority handle',async()=>{const f=fixture({authorize:async()=>true});assert.equal((await f.join()).code,'join_failed');assert.equal(f.log.includes('join'),false);});
test('all optional features require separate integration and never trigger IO',async()=>{const f=fixture();await f.join();const before=[...f.log];for(const name of ['agent-invite','recording','transcript'])assert.deepEqual(f.app.requestExtra(name),{ok:false,code:'feature_not_integrated'});assert.deepEqual(f.log,before);f.app.end();});
test('stop evidence does not invent local or remote success after track failure',async()=>{const broken=track(),fine=track();broken.stop=()=>{throw new Error('private');};const f=fixture({acquire:async()=>stream([broken,fine])});await f.join();await f.app.enableMicrophone();const evidence=f.app.end().localEvidence;assert.equal(evidence.observedLocalTracks,2);assert.equal(evidence.stopCallsReturned,1);assert.equal(evidence.stopCallFailures,1);assert.equal(evidence.endedLocallyObserved,1);assert.equal(evidence.remoteTerminationVerified,false);assert.equal(broken.enabled,false);});
test('async disposal failure does not block local stop or leak rejection',async()=>{const p=deferred(),f=fixture({prepare:async()=>({commit(){},dispose:()=>p.promise})});await f.join();await f.app.enableMicrophone();f.app.end();assert.equal(f.made[0].readyState,'ended');assert.ok(f.app.snapshot().localEvidence.pendingDisposals>0);p.reject(new Error('private'));await flush();assert.equal(f.app.snapshot().localEvidence.disposalFailures,1);});
test('reentrant authorize revocation cannot start a transport join',async()=>{const f=fixture();f.port.authorize=()=>{f.app.revoke();return {};};assert.equal((await f.join()).code,'stale');assert.equal(f.log.includes('join'),false);});
test('reentrant acquire cancellation still stops returned stream',async()=>{const t=track(),f=fixture();await f.join();f.port.acquire=()=>{f.app.cancel();return stream([t]);};await f.app.enableMicrophone();await flush();assert.equal(t.readyState,'ended');assert.equal(f.log.includes('prepare'),false);});
test('non-audio stream is rejected and all its tracks stopped',async()=>{const t=track();t.kind='video';const f=fixture({acquire:async()=>stream([t])});await f.join();assert.equal((await f.app.enableMicrophone()).code,'microphone_failed');assert.equal(t.readyState,'ended');f.app.end();});
test('observer throws do not change operation results',async()=>{const f=fixture({onState(){throw Error('private');}});assert.equal((await f.join()).ok,true);await f.app.enableMicrophone();f.app.end();await flush();});
test('late microphone admission after mute never requests permission',async()=>{const p=deferred(),f=fixture();await f.join();f.port.authorize=()=>p.promise;const job=f.app.enableMicrophone();await flush();f.app.mute();assert.equal((await job).code,'stale');p.resolve({});await flush();assert.equal(f.log.includes('acquire'),false);f.app.end();});
test('commit failure stops capture and disposes staged publication',async()=>{let disposed=0;const f=fixture({prepare:async()=>({commit(){throw new Error('private');},dispose(){disposed++;}})});await f.join();assert.equal((await f.app.enableMicrophone()).code,'microphone_failed');assert.equal(f.made[0].readyState,'ended');assert.equal(disposed,1);assert.equal(f.app.snapshot().state,'listening');f.app.end();});
test('one track disable failure never prevents stopping other acquired tracks',async()=>{const bad=track(),good=track();Object.defineProperty(bad,'enabled',{get:()=>true,set(){throw new Error('private');}});bad.stop=function(){this.stops++;this.readyState='ended';};const f=fixture({acquire:async()=>stream([bad,good])});await f.join();assert.equal((await f.app.enableMicrophone()).code,'microphone_failed');assert.equal(bad.readyState,'ended');assert.equal(good.readyState,'ended');assert.equal(f.app.snapshot().localEvidence.disableFailures,1);f.app.end();});
test('malformed identity update fails closed and stops previous local call',async()=>{const f=fixture();await f.join();await f.app.enableMicrophone();assert.equal(f.app.setIdentity({accountId:'B'}).code,'invalid_identity');assert.equal(f.made[0].readyState,'ended');assert.equal((await f.join()).code,'identity_required');});
test('one-to-one joins listening and disposed instance cannot reacquire',async()=>{const f=fixture();assert.equal((await f.app.join({roomId:'peer-room',mode:'one-to-one'})).ok,true);assert.equal(f.app.snapshot().microphone,'off');f.app.dispose();assert.equal((await f.join()).code,'disposed');assert.equal((await f.app.enableMicrophone()).code,'not_listening');assert.equal(f.log.includes('acquire'),false);});
test('malformed transport resource fails with closed code and cleanup evidence',async()=>{const f=fixture({join:async()=>true});assert.equal((await f.join()).code,'join_failed');assert.equal(f.app.snapshot().localEvidence.disposalFailures,1);});
