import test from 'node:test';
import assert from 'node:assert/strict';
import {createCallLifecycle} from './lifecycle.mjs';
const flush=async()=>{for(let i=0;i<40;i++)await Promise.resolve();};
const track=()=>({kind:'audio',enabled:true,readyState:'live',stop(){this.enabled=false;this.readyState='ended';}});
const join=app=>app.join({roomId:'R',mode:'group'});
function make(ports={}){const app=createCallLifecycle({host:{authorize:ports.authorize||(()=>({}))},media:{acquire:ports.acquire||(()=>({getTracks:()=>[track()]}))},transport:{join:ports.join||(()=>({close(){},preparePublication(){return{commit(){},dispose(){}};}}))}});app.setIdentity({accountId:'A',deviceId:'D'});return app;}
for(const next of [{accountId:'B',deviceId:'D'},{accountId:'A',deviceId:'E'},null,{accountId:'B'}])test('identity teardown forbids close->join '+JSON.stringify(next),async()=>{
 let app,reentry;const scopes=[];app=make({authorize:scope=>{scopes.push(scope);return{};},join:()=>({close(){reentry=join(app);},preparePublication(){}})});await join(app);app.setIdentity(next);await flush();assert.equal((await reentry).code,'call_transition');assert.equal(scopes.length,1);assert.equal(app.snapshot().state,'ended');assert.equal(app.snapshot().capacity.occupied,0);
 app.setIdentity({accountId:'A',deviceId:'D'});await join(app);assert.equal(scopes.at(-1).accountId,'A');assert.equal(scopes.at(-1).generation,2);app.dispose();
});
test('dispose barrier prevents any reentrant ownership reservation',async()=>{let app,reentry,authorizations=0;app=make({authorize:()=>{authorizations++;return{};},join:()=>({close(){reentry=join(app);},preparePublication(){}})});await join(app);app.dispose();assert.equal((await reentry).code,'disposed');await flush();assert.equal(app.snapshot().state,'disposed');assert.equal(app.snapshot().capacity.occupied,0);assert.equal(authorizations,1);});
test('session close getter cancels before listening state commit',async()=>{let app,once=false,closes=0,prepareReads=0;app=make({join:()=>({get close(){if(!once){once=true;app.cancel();}return()=>{closes++;};},get preparePublication(){prepareReads++;return()=>{};}})});assert.equal((await join(app)).code,'stale');await flush();assert.equal(app.snapshot().state,'ended');assert.equal(app.snapshot().capacity.occupied,0);assert.equal(closes,1);assert.equal(prepareReads,0);});
for(const field of ['dispose','commit'])test('stage '+field+' getter mutes before any commit dispatch',async()=>{let app,once=false,commits=0,disposals=0;const t=track(),stage={};Object.defineProperties(stage,{dispose:{get(){if(field==='dispose'&&!once){once=true;app.mute();}return()=>{disposals++;};}},commit:{get(){if(field==='commit'&&!once){once=true;app.mute();}return()=>{commits++;};}}});app=make({acquire:()=>({getTracks:()=>[t]}),join:()=>({close(){},preparePublication:()=>stage})});await join(app);assert.equal((await app.enableMicrophone()).code,'stale');await flush();assert.equal(commits,0);assert.equal(disposals,1);assert.equal(t.readyState,'ended');assert.equal(app.snapshot().microphone,'off');app.end();});
test('Array throwing iterator is never invoked and all own data tracks stop; malformed slot quarantined',async()=>{const tracks=[track(),track()];let reads=0;tracks[Symbol.iterator]=function*(){reads++;yield tracks[0];throw Error('private');};const app=make({acquire:()=>({getTracks:()=>tracks})});await join(app);assert.equal((await app.enableMicrophone()).code,'microphone_failed');assert.equal(reads,0);assert.equal(tracks[0].readyState,'ended');assert.equal(tracks[1].readyState,'ended');await flush();assert.equal(app.snapshot().capacity.occupied,2);app.end();});
for(const shape of ['gap','accessor','descriptor-throws','prototype-throws'])test('unknown array shape '+shape+' stops known tracks and never reads accessor',async()=>{
 const t=track(),last=track();let reads=0;let tracks=[t,track(),last];
 if(shape==='gap')delete tracks[1];
 if(shape==='accessor')Object.defineProperty(tracks,'1',{get(){reads++;throw Error('private');},configurable:true});
 if(shape==='descriptor-throws')tracks=new Proxy(tracks,{getOwnPropertyDescriptor(target,key){if(key==='1')throw Error('private');return Reflect.getOwnPropertyDescriptor(target,key);}});
 if(shape==='prototype-throws')tracks=new Proxy(tracks,{getPrototypeOf(){throw Error('private');}});
 const app=make({acquire:()=>({getTracks:()=>tracks})});await join(app);assert.equal((await app.enableMicrophone()).code,'microphone_failed');await flush();assert.equal(reads,0);assert.equal(t.readyState,'ended');assert.equal(last.readyState,'ended');assert.equal(app.snapshot().capacity.occupied,2);app.end();
});
test('mute stop callback cannot reentrantly acquire another microphone',async()=>{let app,reentry;const t=track();const oldStop=t.stop;t.stop=function(){reentry=app.enableMicrophone();oldStop.call(this);};app=make({acquire:()=>({getTracks:()=>[t]})});await join(app);await app.enableMicrophone();app.mute();assert.equal((await reentry).code,'call_transition');await flush();assert.equal(app.snapshot().microphone,'off');assert.equal(app.snapshot().capacity.occupied,1);app.end();});
