import test from 'node:test';
import {mkdtemp,writeFile,rm,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {readApprovedPolicy,policyTarget,policySetting} from './application-policy.mjs';
import assert from 'node:assert/strict';
import {Rollout,createConfig,preservationHash} from './rollout.mjs';
import {SafeError} from './docker-api.mjs';
import {productionMaintenance,modelReadiness} from './runtime.mjs';
const modelProxies={agentModelProxy:{ready:true,model:'DeepSeek-V4-Flash-0731',transport:'server-proxy'},applicationModelProxy:{ready:true,model:'DeepSeek-V4-Flash-0731',transport:'application-token-server-proxy',path:'/api/inference/v1/chat/completions'}};
const args={originalId:'a'.repeat(64),originalImage:'sha256:'+'d'.repeat(64),candidateImage:'sha256:'+'c'.repeat(64),revision:'e'.repeat(40),transaction:'f'.repeat(20)};
const original=()=>({Id:args.originalId,Image:args.originalImage,Name:'/soty-online-chat',State:{Running:true,Status:'running'},Config:{Image:args.originalImage,Env:['TOKEN=synthetic-sensitive','SOTY_CODEX_SESSION=preserved','SOTY_TRAFFIC_TARGET=unchanged'],Labels:{owner:'original'},Hostname:'existing-host',User:'123:456',Cmd:['node','server/index.js'],WorkingDir:'/app',Volumes:{'/data':{}},Healthcheck:{Test:['CMD','node','probe.js']}},HostConfig:{Binds:['/synthetic/tokens:/run/tokens:ro'],Memory:1073741824,NanoCpus:1500000000,PidsLimit:180,PortBindings:{'8080/tcp':[{HostIp:'127.0.0.1',HostPort:'18182'}]},NetworkMode:'soty',RestartPolicy:{Name:'unless-stopped'},ReadonlyRootfs:false,CapDrop:['NET_RAW'],SecurityOpt:['no-new-privileges']},Mounts:[{Type:'volume',Name:'synthetic-data',Destination:'/data',RW:true}],NetworkSettings:{Networks:{soty:{IPAMConfig:null,Aliases:['preserved-alias'],DriverOpts:{},NetworkID:'runtime-only',IPAddress:'172.28.0.3'}}}});
function fixture(fault={}) {
 const map=new Map([[args.originalId,original()],['sentinel',{Id:'sentinel',State:{Running:true},Name:'/independent-task'}]]),events=[],records=[];let n=0,maintenance=false,statusCalls=0,migrated=false;
 const lookup=id=>map.get(id)||[...map.values()].find(c=>c.Name==='/'+id);
 function fail(op,when){if(fault.op===op&&fault.when===when&&!fault.used){fault.used=true;throw new SafeError(when==='after'?'engine_response_ambiguous':'injected_failure');}}
 const engine={
 async inspect(id){const c=lookup(id);if(!c)throw new SafeError('engine_http_404');return structuredClone(c);},
 async image(){return {Id:args.candidateImage,Config:{Labels:{'org.opencontainers.image.revision':args.revision}}};},
 async create(name,body){events.push('create:'+name);fail('create','before');const {HostConfig,NetworkingConfig,...Config}=structuredClone(body);const Id=(++n).toString(16).padStart(64,'0');map.set(Id,{Id,Image:body.Image,Name:'/'+name,Config,HostConfig,Mounts:[],NetworkSettings:{Networks:NetworkingConfig?.EndpointsConfig||{}},State:{Running:false,Status:'created'}});fail('create','after');return {Id};},
 async stop(id){events.push('stop:'+id);fail(id===args.originalId?'stop-old':'stop-candidate','before');Object.assign(map.get(id).State,{Running:false,Status:'exited'});fail(id===args.originalId?'stop-old':'stop-candidate','after');},
 async rename(id,name){const op=id===args.originalId?'rename-old':'rename-candidate';events.push(op);fail(op,'before');if([...map.values()].some(c=>c.Id!==id&&c.Name==='/'+name))throw new SafeError('name_conflict');map.get(id).Name='/'+name;fail(op,'after');},
 async start(id){const c=map.get(id),op=id===args.originalId?'start-old':'start-candidate';events.push(op);fail(op,'before');Object.assign(c.State,{Running:true,Status:'running'});if(c.Config.Labels?.['io.soty.connector-rollout.helper'])Object.assign(c.State,{Running:false,Status:'exited',ExitCode:0});fail(op,'after');},
 async remove(id){events.push('remove:'+id);map.delete(id);},
 async helperOutput(){return {ok:true,activeJobs:[],count:0,maintenance:false,schema:'legacy'};}
 };
 const helper=async verb=>{events.push('helper:'+verb);fail('helper-'+verb,'before');if(verb==='enter')maintenance=true;if(verb==='leave')maintenance=false;if(verb==='rollback'){if(fault.rollbackFailure)throw new SafeError('rollback_failed');migrated=false;}
 const raced=verb==='status'&&((++statusCalls===2&&fault.race)||fault.active);fail('helper-'+verb,'after');return {ok:true,count:raced?1:0,activeJobs:raced?[{id:'raced-job',status:'queued'}]:[],maintenance,schema:'synthetic'};};
 const ready=async kind=>{events.push('ready:'+kind);if(kind==='candidate'){migrated=true;fail('readiness','before');return {ok:true,storageReady:true,maintenance:true,schema:'soty.connector-storage-ready.v1',modelProxies};}return {ok:true,modelProxies};};
 const run=new Rollout({engine,maintenance:helper,ready,record:async s=>records.push(s),attempts:2,sleep:async()=>{}});
 return {run,engine,map,events,records,get migrated(){return migrated;}};
}
test('configuration and anonymous volume preserve exact protected values without journal disclosure',async()=>{const f=fixture();await f.run.prepare(args);const c=f.run.config;assert.deepEqual(c.Env,original().Config.Env);assert.deepEqual(c.HostConfig.PortBindings,original().HostConfig.PortBindings);assert.equal(c.HostConfig.Memory,1073741824);assert.equal(c.HostConfig.Mounts[0].Source,'synthetic-data');assert.deepEqual(c.NetworkingConfig.EndpointsConfig.soty.Aliases,['preserved-alias']);assert.doesNotMatch(JSON.stringify(f.records),/synthetic-sensitive|SOTY_CODEX|SOTY_TRAFFIC|\/synthetic\/tokens/);assert.equal(f.run.state.configurationSha256,preservationHash(c));});
test('normal success creates before stop and offline check before migration/admission',async()=>{const f=fixture();await f.run.prepare(args);await f.run.promote();assert.equal(f.run.state.phase,'committed');assert.ok(f.events.find(e=>e.startsWith('create:')));assert.ok(f.events.indexOf('helper:enter')>f.events.indexOf('stop:'+args.originalId));assert.ok(f.events.indexOf('helper:leave')>f.events.indexOf('ready:candidate'));assert.equal(f.map.get(args.originalId).State.Running,false);assert.equal(f.map.get('sentinel').State.Running,true);});
for(const op of ['create','stop-old','rename-old','rename-candidate','start-candidate'])test('applied but dropped '+op+' is reconciled without duplicate',async()=>{const f=fixture({op,when:'after'});await f.run.prepare(args);await f.run.promote();assert.equal(f.run.state.phase,'committed');assert.equal([...f.map.values()].filter(c=>c.Image===args.candidateImage).length,1);assert.equal(f.map.get('sentinel').State.Running,true);});
for(const op of ['rename-old','rename-candidate','start-candidate','readiness'])test('failure '+op+' restores same original ID',async()=>{const f=fixture({op,when:'before'});await f.run.prepare(args);await assert.rejects(f.run.promote());assert.equal(f.run.state.phase,'restored');assert.equal(f.map.get(args.originalId).Name,'/soty-online-chat');assert.equal(f.map.get(args.originalId).State.Running,true);assert.equal(f.map.get('sentinel').State.Running,true);assert.ok(f.events.indexOf('helper:leave')>f.events.indexOf('ready:original'));});
test('admission race aborts before enter/migration and restarts old exact ID',async()=>{const f=fixture({race:true});await f.run.prepare(args);await assert.rejects(f.run.promote(),/offline_admission_race/);assert.equal(f.run.state.phase,'restored');assert.ok(!f.events.includes('helper:enter'));assert.ok(!f.events.includes('helper:rollback'));assert.equal(f.migrated,false);});
test('restore failure is explicit, never falsely restored',async()=>{const f=fixture({op:'readiness',when:'before',rollbackFailure:true});await f.run.prepare(args);await assert.rejects(f.run.promote(),/recovery_required/);assert.equal(f.run.state.phase,'recovery_required');assert.equal(f.map.get(args.originalId).State.Running,false);});
test('dropped leave reconciles marker, never rollback after reopening',async()=>{const f=fixture({op:'helper-leave',when:'after'});await f.run.prepare(args);await f.run.promote();assert.equal(f.run.state.phase,'committed');assert.ok(!f.events.includes('helper:rollback'));});
test('helper uses same mounts and Env in memory but no ports/network/capabilities',async()=>{const f=fixture();await f.run.prepare(args);const maint=productionMaintenance(f.engine,{sleep:async()=>{},maxPolls:2});const created=[];const oldCreate=f.engine.create;f.engine.create=async(n,c)=>{created.push(c);return oldCreate(n,c);};await maint('status',f.run);const c=created[0];assert.deepEqual(c.Env,original().Config.Env);assert.equal(c.HostConfig.NetworkMode,'none');assert.equal(c.HostConfig.PortBindings,undefined);assert.equal(c.HostConfig.Memory,805306368);assert.equal(c.HostConfig.Mounts[0].Source,'synthetic-data');assert.deepEqual(c.Cmd,['server/connector-maintenance.js','status']);});

test('preexisting active jobs abort without stopping original',async()=>{const f=fixture({active:true});await f.run.prepare(args);await assert.rejects(f.run.promote(),/precheck_not_quiescent/);assert.equal(f.run.state.phase,'aborted');assert.ok(!f.events.some(e=>e.startsWith('stop:')));});
test('unknown status fails closed before stop',async()=>{const f=fixture();await f.run.prepare(args);f.run.maintenance=async()=>({ok:false});await assert.rejects(f.run.promote(),/maintenance_status_invalid/);assert.equal(f.run.state.phase,'aborted');});
test('stop error with confirmed old still running is safe abort',async()=>{const f=fixture({op:'stop-old',when:'before'});await f.run.prepare(args);await assert.rejects(f.run.promote());assert.equal(f.run.state.phase,'aborted');assert.equal(f.map.get(args.originalId).State.Running,true);});
test('unresolved stop does not claim old restored while a delayed operation can still stop it',async()=>{const f=fixture();await f.run.prepare(args);f.engine.stop=async()=>{throw new SafeError('engine_response_ambiguous');};await assert.rejects(f.run.promote(),/recovery_required/);assert.equal(f.run.state.phase,'recovery_required');});
test('candidate revision mismatch makes no container mutation',async()=>{const f=fixture();f.engine.image=async()=>({Id:args.candidateImage,Config:{Labels:{}}});await assert.rejects(f.run.prepare(args),/candidate_revision_mismatch/);assert.ok(!f.events.some(e=>e.startsWith('create:')));});
test('configuration tamper refuses prepare without touching original',async()=>{const f=fixture();const create=f.engine.create;f.engine.create=async(n,c)=>create(n,{...c,Env:['tampered']});await assert.rejects(f.run.prepare(args),/candidate_configuration_mismatch/);assert.equal(f.map.get(args.originalId).State.Running,true);});
test('unresolved maintenance helper after stop retains recovery barrier',async()=>{const f=fixture();await f.run.prepare(args);const helper=f.run.maintenance;f.run.maintenance=async(v)=>{if(v==='enter')throw new SafeError('maintenance_helper_unresolved');return helper(v);};await assert.rejects(f.run.promote(),/maintenance_helper_unresolved/);assert.equal(f.run.state.phase,'recovery_required');assert.equal(f.map.get(args.originalId).State.Running,false);assert.ok(!f.events.includes('helper:rollback'));});

test('applied but dropped enter is reconciled from offline marker before candidate start',async()=>{const f=fixture({op:'helper-enter',when:'after'});await f.run.prepare(args);await f.run.promote();assert.equal(f.run.state.phase,'committed');assert.equal(f.events.filter(e=>e==='helper:enter').length,1);});


test('revision label is exact and exempt only from preservation delta',async()=>{const f=fixture();f.map.get(args.originalId).Config.Labels['org.opencontainers.image.revision']='b'.repeat(40);await f.run.prepare(args);assert.equal(f.run.candidate.Config.Labels['org.opencontainers.image.revision'],args.revision);f.map.get(f.run.candidate.Id).Config.Labels['org.opencontainers.image.revision']='b'.repeat(40);await assert.rejects(f.run.promote(),/candidate_ownership_mismatch/);assert.ok(!f.events.some(e=>e.startsWith('stop:')));});
test('candidate protected configuration drift fails before original stop',async()=>{const f=fixture();await f.run.prepare(args);f.map.get(f.run.candidate.Id).Config.Env.push('UNREVIEWED=1');await assert.rejects(f.run.promote(),/candidate_configuration_mismatch/);assert.ok(!f.events.some(e=>e.startsWith('stop:')));});
test('candidate application readiness mismatch restores before admission',async()=>{const f=fixture();await f.run.prepare(args);const ready=f.run.ready;f.run.ready=async kind=>{const r=await ready(kind);return kind==='candidate'?{...r,modelProxies:{...modelProxies,applicationModelProxy:{...modelProxies.applicationModelProxy,ready:false}}}:r;};await assert.rejects(f.run.promote(),/candidate_model_readiness_changed/);assert.equal(f.run.state.phase,'restored');});
test('health ok alone cannot hide missing or broken model proxy configuration',()=>{assert.throws(()=>modelReadiness({ok:true}),/model_readiness_failed/);assert.throws(()=>modelReadiness({...modelProxies,applicationModelProxy:{...modelProxies.applicationModelProxy,ready:false}}),/model_readiness_failed/);assert.deepEqual(modelReadiness(modelProxies),modelProxies);});

async function policyFixture(fn){const dir=await mkdtemp(path.join(await realpath(tmpdir()),'soty-reviewed-policy-'));try{const source=path.join(dir,'policy.json');const value={schema:'soty.application-model-policy.v1',applications:[{id:'kvartalufa',allowedModels:['deepseek-ai/DeepSeek-V4-Flash-0731','MiniMaxAI/MiniMax-M2.7']}]};const bytes=JSON.stringify(value);await writeFile(source,bytes);const sha256=createHash('sha256').update(bytes).digest('hex');await fn({source,sha256,value,policy:await readApprovedPolicy(source,sha256)});}finally{await rm(dir,{recursive:true,force:true});}}
test('reviewed application rule adds only one pathname env and one readonly nonsecret mount',async()=>policyFixture(async({policy})=>{const f=fixture();await f.run.prepare({...args,applicationPolicy:policy});const c=f.run.candidate;assert.deepEqual(c.Config.Env,original().Config.Env.concat(`${policySetting}=${policyTarget}`));assert.deepEqual(c.HostConfig.Mounts.at(-1),{Type:'bind',Source:policy.source,Target:policyTarget,ReadOnly:true});assert.equal(f.run.state.applicationPolicySha256,policy.sha256);await f.run.promote();assert.equal(f.run.state.phase,'committed');assert.deepEqual(f.map.get(args.originalId).Config.Env,original().Config.Env);}));
test('changed reviewed policy hash fails before original stop',async()=>policyFixture(async({source,policy})=>{const f=fixture();await f.run.prepare({...args,applicationPolicy:policy});await writeFile(source,'{}');await assert.rejects(f.run.promote(),/policy_hash_mismatch/);assert.ok(!f.events.some(e=>e.startsWith('stop:')));}));
test('policy for another application is rejected even with its exact byte hash',async()=>policyFixture(async({source,value})=>{value.applications[0].id='other';const bytes=JSON.stringify(value);await writeFile(source,bytes);await assert.rejects(readApprovedPolicy(source,createHash('sha256').update(bytes).digest('hex')),/policy_scope_mismatch/);}));
test('policy downgrade before admission restores same original without added env or mount',async()=>policyFixture(async({policy})=>{const f=fixture({op:'readiness',when:'before'});await f.run.prepare({...args,applicationPolicy:policy});await assert.rejects(f.run.promote());assert.equal(f.run.state.phase,'restored');assert.deepEqual(f.map.get(args.originalId).Config.Env,original().Config.Env);assert.equal(f.map.get(args.originalId).HostConfig.Mounts,undefined);}));
