import test from 'node:test';
import assert from 'node:assert/strict';
import {createManagedReviewsPort} from '../server/managed-port.mjs';
import {contractDigest} from '../../app-contract/json.mjs';
const actor={accountId:'owner',deviceId:'device'},subject={kind:'app',id:'app'},args={appId:'app',localSubject:subject,requestId:'request',title:'Title'};
const ref={id:'povedai:managed',version:1,digest:contractDigest({protocol:'povedai.managed-reviews.v1'})};
const context=()=>({appId:'app',ownerId:'owner',accountId:'owner',appRevision:1,policyEpoch:1,target:{revision:1,digest:'a'.repeat(64),profile:'fixture'},entry:{origin:'https://app.example',path:'/'},canManage:true});
const receipt=()=>({protocol:'povedai.managed-reviews.v1',localSubject:subject,entityType:'product',bindingId:'binding',siteId:'site',siteKey:'site-key',objectId:'object',objectSlug:'object-slug',subjectId:'subject',placementId:'placement',generation:1,canDisplay:false});
function fixture(overrides={}){let calls=0;const source={withActor:async(_credential,callback)=>callback({}),...Object.fromEntries(['provision','context','list','collect','publish','moderate'].map(op=>[op,async()=>{calls++;return receipt();}]))};
  const port=createManagedReviewsPort({registryId:'soty',environmentId:'test',providerRef:ref,actorActive:()=>true,withAppAuthority:(_request,callback)=>callback(context()),resolveSourceCredential:async()=>Object.freeze({opaque:'private-host-only'}),source,...overrides});return{port,calls:()=>calls,source};}
test('trusted Source projection returns host-scoped pins; author cannot submit scope/provider/permissions',async()=>{const f=fixture();const result=await f.port.execute({op:'provision',actor,args});assert.equal(result.canDisplay,false);assert.equal(result.providerRef.digest,ref.digest);assert.match(result.subjectRef.digest,/^[a-f0-9]{64}$/u);
  for(const extra of [{scope:{tenantId:'other'}},{providerRef:ref},{rights:['publish']},{origin:'https://evil.example'},{source:{handler:'exec'}}])await assert.rejects(f.port.execute({op:'provision',actor,args:{...args,...extra}}),/managed_reviews_invalid/u);assert.equal(f.calls(),1);f.port.close();});
test('app/root change, swallowed duplicate/late callbacks and wrong Source tuple deny acknowledgement',async()=>{let held,rev=1;const f=fixture({withAppAuthority:(_request,callback)=>{held=callback;return callback({...context(),appRevision:rev});}});f.source.provision=async()=>receipt(); // Factory captures methods; test a fresh factory for altered host behavior.
  const g=fixture({source:{...f.source,provision:async()=>{rev++;return receipt();}}}); // g uses its own stable authority; use below exact port.
  g.port.close();const changed=fixture({withAppAuthority:(_request,callback)=>callback({...context(),appRevision:rev}),source:{...f.source,provision:async()=>{rev++;return receipt();}}});await assert.rejects(changed.port.execute({op:'provision',actor,args}),/managed_reviews_authority_changed/u);
  const late=fixture({withAppAuthority:(_request,callback)=>{held=callback;return callback(context());},source:{...f.source,provision:async()=>{try{held(context());}catch{}return receipt();}}});await assert.rejects(late.port.execute({op:'provision',actor,args}),/managed_reviews_authority_invalid/u);
  const duplicate=fixture({withAppAuthority:(_request,callback)=>{const value=callback(context());try{callback(context());}catch{}return value;}});await assert.rejects(duplicate.port.execute({op:'provision',actor,args}),/managed_reviews_authority_invalid/u);
  const wrong=fixture({source:{...f.source,provision:async()=>({...receipt(),localSubject:{kind:'person',id:'other'}})}});await assert.rejects(wrong.port.execute({op:'provision',actor,args}),/managed_reviews_source_projection_invalid/u);[f,changed,late,duplicate,wrong].forEach(f=>f.port.close());});
test('input captured before async resolution; timeout retains four actual unresolved source slots and never retries',async()=>{let resolveCredential;const f=fixture({resolveSourceCredential:()=>new Promise(resolve=>{resolveCredential=resolve;})});const input=structuredClone(args),future=f.port.execute({op:'provision',actor,args:input});input.localSubject.id='other';await Promise.resolve();resolveCredential({});assert.equal((await future).localSubject.id,'app');f.port.close();
  let sourceCalls=0;const unresolved=fixture({timeoutMs:100,source:{...f.source,provision:()=>{sourceCalls++;return new Promise(()=>{});}}});for(let i=0;i<4;i++)await assert.rejects(unresolved.port.execute({op:'provision',actor,args:{...args,requestId:'timeout-'+i}}),/managed_reviews_timeout/u);await assert.rejects(unresolved.port.execute({op:'provision',actor,args}),/managed_reviews_busy/u);assert.equal(sourceCalls,4);unresolved.port.close();});
