import test from 'node:test';
import assert from 'node:assert/strict';
import {createManagedReviewsPort} from '../server/managed-port.mjs';
import {contractDigest} from '../../app-contract/json.mjs';
const actor={accountId:'owner',deviceId:'device'},subject={kind:'app',id:'app'},args={appId:'app',localSubject:subject,requestId:'request',title:'Title'};
const ref={id:'povedai:managed',version:1,digest:contractDigest({protocol:'povedai.managed-reviews.v1'})};
const context=()=>({appId:'app',ownerId:'owner',accountId:'owner',appRevision:1,policyEpoch:1,target:{revision:1,digest:'a'.repeat(64),profile:'fixture'},entry:{origin:'https://app.example',path:'/'},canManage:true});
const receipt=()=>({protocol:'povedai.managed-reviews.v1',localSubject:subject,entityType:'product',bindingId:'binding',siteId:'site',siteKey:'site-key',objectId:'object',objectSlug:'object-slug',subjectId:'subject',placementId:'placement',generation:1,canDisplay:false});
function fixture(overrides={}){let calls=0;const source={withActor:async(_credential,callback)=>callback({}),...Object.fromEntries(['provision','context','list','collect','publish','moderate'].map(op=>[op,async()=>{calls++;return receipt();}]))};
  const port=createManagedReviewsPort({registryId:'soty',environmentId:'test',providerRef:ref,withRootActorAuthority:(original,callback)=>{assert.equal(original,actor);return callback(actor);},withAppAuthority:(_request,callback)=>callback(context()),resolveSourceCredential:async()=>Object.freeze({opaque:'private-host-only'}),source,...overrides});return{port,calls:()=>calls,source};}
test('trusted Source projection returns host-scoped pins; author cannot submit scope/provider/permissions',async()=>{const f=fixture();const result=await f.port.execute({op:'provision',actor,args});assert.equal(result.canDisplay,false);assert.equal(result.providerRef.digest,ref.digest);assert.match(result.subjectRef.digest,/^[a-f0-9]{64}$/u);
  for(const extra of [{scope:{tenantId:'other'}},{providerRef:ref},{rights:['publish']},{origin:'https://evil.example'},{source:{handler:'exec'}}])await assert.rejects(f.port.execute({op:'provision',actor,args:{...args,...extra}}),/managed_reviews_invalid/u);assert.equal(f.calls(),1);f.port.close();});
test('app/root change, swallowed duplicate/late callbacks and wrong Source tuple deny acknowledgement',async()=>{let held,rev=1;const f=fixture({withAppAuthority:(_request,callback)=>{held=callback;return callback({...context(),appRevision:rev});}});f.source.provision=async()=>receipt(); // Factory captures methods; test a fresh factory for altered host behavior.
  const g=fixture({source:{...f.source,provision:async()=>{rev++;return receipt();}}}); // g uses its own stable authority; use below exact port.
  g.port.close();const changed=fixture({withAppAuthority:(_request,callback)=>callback({...context(),appRevision:rev}),source:{...f.source,provision:async()=>{rev++;return receipt();}}});await assert.rejects(changed.port.execute({op:'provision',actor,args}),/managed_reviews_authority_changed/u);
  const late=fixture({withAppAuthority:(_request,callback)=>{held=callback;return callback(context());},source:{...f.source,provision:async()=>{try{held(context());}catch{}return receipt();}}});await assert.rejects(late.port.execute({op:'provision',actor,args}),/managed_reviews_authority_invalid/u);
  const duplicate=fixture({withAppAuthority:(_request,callback)=>{const value=callback(context());try{callback(context());}catch{}return value;}});await assert.rejects(duplicate.port.execute({op:'provision',actor,args}),/managed_reviews_authority_invalid/u);
  const wrong=fixture({source:{...f.source,provision:async()=>({...receipt(),localSubject:{kind:'person',id:'other'}})}});await assert.rejects(wrong.port.execute({op:'provision',actor,args}),/managed_reviews_source_projection_invalid/u);[f,changed,late,duplicate,wrong].forEach(f=>f.port.close());});
test('input captured before async resolution; timeout retains four actual unresolved source slots and never retries',async()=>{let resolveCredential;const f=fixture({resolveSourceCredential:()=>new Promise(resolve=>{resolveCredential=resolve;})});const input=structuredClone(args),future=f.port.execute({op:'provision',actor,args:input});input.localSubject.id='other';await Promise.resolve();resolveCredential({});assert.equal((await future).localSubject.id,'app');f.port.close();
  let sourceCalls=0;const unresolved=fixture({timeoutMs:100,source:{...f.source,provision:()=>{sourceCalls++;return new Promise(()=>{});}}});for(let i=0;i<4;i++)await assert.rejects(unresolved.port.execute({op:'provision',actor,args:{...args,requestId:'timeout-'+i}}),/managed_reviews_timeout/u);await assert.rejects(unresolved.port.execute({op:'provision',actor,args}),/managed_reviews_busy/u);assert.equal(sourceCalls,4);unresolved.port.close();});

test('original actor proof and verified owner metadata remain separate; changed proof during credential await denies Source dispatch',async()=>{
  let active=true,resolve,calls=0;const f=fixture({withRootActorAuthority:(original,callback)=>{assert.equal(original,actor);if(!active)throw new Error('revoked');return callback(actor);},resolveSourceCredential:()=>new Promise(done=>{resolve=done;}),source:{withActor:async(_credential,callback)=>callback({}),...Object.fromEntries(['provision','context','list','collect','publish','moderate'].map(op=>[op,async()=>{calls++;return receipt();}]))}});
  const pending=f.port.execute({op:'provision',actor,args});await Promise.resolve();active=false;resolve({});await assert.rejects(pending,/managed_reviews_source_unavailable/u);assert.equal(calls,0);f.port.close();
  assert.throws(()=>fixture({withRootActorAuthority:undefined}),/managed_reviews_host_required/u,'field-based actorActive alone is not a proof port');
});

test('Root proof callbacks cannot be skipped, async, repeated, or retained across Source await',async()=>{
  const skipped=fixture({withRootActorAuthority:()=>actor});await assert.rejects(skipped.port.execute({op:'provision',actor,args}),/managed_reviews_authority_invalid/u);assert.equal(skipped.calls(),0);
  const asynchronous=fixture({withRootActorAuthority:async(_original,callback)=>callback(actor)});await assert.rejects(asynchronous.port.execute({op:'provision',actor,args}),/managed_reviews_async_authority/u);assert.equal(asynchronous.calls(),0);
  const duplicate=fixture({withRootActorAuthority:(_original,callback)=>{const value=callback(actor);try{callback(actor);}catch{}return value;}});await assert.rejects(duplicate.port.execute({op:'provision',actor,args}),/managed_reviews_authority_invalid/u);assert.equal(duplicate.calls(),0);
  let held;const late=fixture({withRootActorAuthority:(_original,callback)=>{held=callback;return callback(actor);},resolveSourceCredential:async()=>{try{held(actor);}catch{}return{};}});await assert.rejects(late.port.execute({op:'provision',actor,args}),/managed_reviews_authority_invalid/u);assert.equal(late.calls(),0);
  const duringSource=fixture({withRootActorAuthority:(_original,callback)=>{held=callback;return callback(actor);},source:{...late.source,provision:async()=>{try{held(actor);}catch{}return receipt();}}});await assert.rejects(duringSource.port.execute({op:'provision',actor,args}),/managed_reviews_authority_invalid/u,'the post-credential proof fence remains poisoned even if Source swallows its late callback');
  [skipped,asynchronous,duplicate,late,duringSource].forEach(f=>f.port.close());
});

test('swallowed duplicate/retained Source callbacks cannot re-dispatch or acknowledge a result',async()=>{
  let callbacks=0,held;const twice=fixture({source:{withActor:async(_credential,callback)=>{await callback({});try{await callback({});}catch{}return receipt();},...Object.fromEntries(['provision','context','list','collect','publish','moderate'].map(op=>[op,async()=>{callbacks++;return receipt();}]))}});
  await assert.rejects(twice.port.execute({op:'provision',actor,args}),/managed_reviews_source_authority_invalid/u);assert.equal(callbacks,1);twice.port.close();
  const retained=fixture({source:{withActor:async(_credential,callback)=>{held=callback;return callback({});},...Object.fromEntries(['provision','context','list','collect','publish','moderate'].map(op=>[op,async()=>{callbacks++;return receipt();}]))}});
  await retained.port.execute({op:'provision',actor,args});await assert.rejects(held({}),/managed_reviews_source_authority_invalid/u);assert.equal(callbacks,2);retained.port.close();
});

function nativeReview(){return{id:'review',objectId:'object',subjectId:'subject',type:'review',rootId:'review',depth:0,version:1,source:'widget',status:'pending',appearance:'standard',appearanceMeta:{},body:'Private bounded review',author:{name:'Участник',avatarUrl:undefined,verified:false},mediaUrls:[],tags:[],inferredTags:[],excludedTags:[],up:0,down:0,meta:{},createdAt:'2026-10-07T00:00:00.000Z',updatedAt:'2026-10-07T00:00:00.000Z',authorId:undefined,consentEvidence:undefined};}
function listFixture(item){const f=fixture();f.port.close();return fixture({source:{...f.source,list:async()=>({items:[item],nextCursor:null})}});}
const listArgs={appId:'app',localSubject:subject,limit:10};
test('native list DTO preserves nested reply fields and drops only known native undefined redactions',async()=>{
  const item={...nativeReview(),id:'reply',type:'comment',parentId:'review',depth:1};const f=listFixture(item);const result=await f.port.execute({op:'list',actor,args:listArgs});assert.equal(result.items[0].parentId,'review');assert.equal(result.items[0].depth,1);assert.equal(Object.hasOwn(result.items[0],'authorId'),false);assert.equal(Object.hasOwn(result.items[0].author,'avatarUrl'),false);f.port.close();
});
test('list nested identity claims, metadata, accessors, foreign placements and unsafe URLs fail closed502',async()=>{
  const secrets=[{...nativeReview(),issuer:'https://private.example'}, {...nativeReview(),author:{name:'Name',email:'synthetic@example.test'}},{...nativeReview(),meta:{accessToken:'synthetic'}},{...nativeReview(),appearanceMeta:{script:'synthetic'}},{...nativeReview(),authorId:'private-author'}, {...nativeReview(),unknown:undefined},{...nativeReview(),objectId:'foreign'},{...nativeReview(),subjectId:'foreign'},{...nativeReview(),mediaUrls:['javascript:synthetic']},{...nativeReview(),author:{name:'Name',avatarUrl:'https://synthetic:private@example.test/x'}}];
  let getterCalls=0;const getter=nativeReview();Object.defineProperty(getter.author,'email',{enumerable:true,get(){getterCalls++;return 'synthetic';}});secrets.push(getter);
  for(const item of secrets){const f=listFixture(item);await assert.rejects(f.port.execute({op:'list',actor,args:listArgs}),error=>error.code==='managed_reviews_source_projection_invalid'&&error.status===502);f.port.close();}assert.equal(getterCalls,0);
});
