import { DateTime } from 'luxon';
import { emptyRange, evaluateSignals } from './engine.js';
import type { Entity, PlannerSnapshot, Template, TimeRange, TypeDefinition } from './types.js';

export const builtinTypes: TypeDefinition[] = [
  {
    id: 'event',
    label: 'Событие',
    icon: 'circle',
    color: '#4368f5',
    kind: 'point',
    builtin: true,
    fields: [],
  },
  {
    id: 'period',
    label: 'Период',
    icon: 'calendar-range',
    color: '#6481e8',
    kind: 'period',
    builtin: true,
    fields: [],
  },
  {
    id: 'process',
    label: 'Процесс',
    icon: 'workflow',
    color: '#596cc8',
    kind: 'process',
    builtin: true,
    fields: [],
  },
  {
    id: 'note',
    label: 'Заметка',
    icon: 'sticky-note',
    color: '#c88e2e',
    kind: 'note',
    builtin: true,
    fields: [],
  },
  {
    id: 'metric',
    label: 'Измерение',
    icon: 'activity',
    color: '#2e9b8d',
    kind: 'metric',
    builtin: true,
    fields: [
      { id: 'value', label: 'Значение', type: 'number', required: true },
      { id: 'unit', label: 'Единица', type: 'text' },
    ],
  },
  {
    id: 'trip',
    label: 'Поездка',
    icon: 'plane',
    color: '#2d9b95',
    kind: 'period',
    builtin: true,
    fields: [
      { id: 'destination', label: 'Место', type: 'text' },
      { id: 'budget', label: 'Бюджет', type: 'number' },
    ],
  },
  {
    id: 'vacation',
    label: 'Отпуск',
    icon: 'sun',
    color: '#d4933e',
    kind: 'period',
    builtin: true,
    fields: [{ id: 'destination', label: 'Место', type: 'text' }],
  },
  {
    id: 'learning',
    label: 'Обучение',
    icon: 'graduation-cap',
    color: '#9862c2',
    kind: 'period',
    builtin: true,
    fields: [
      { id: 'subject', label: 'Тема', type: 'text' },
      { id: 'progress', label: 'Прогресс, %', type: 'number' },
    ],
  },
  {
    id: 'meeting',
    label: 'Встреча',
    icon: 'users',
    color: '#6678c9',
    kind: 'point',
    builtin: true,
    fields: [{ id: 'location', label: 'Место или ссылка', type: 'text' }],
  },
  {
    id: 'task',
    label: 'Работа',
    icon: 'check',
    color: '#487bea',
    kind: 'period',
    builtin: true,
    fields: [],
  },
  {
    id: 'delivery',
    label: 'Поставка',
    icon: 'truck',
    color: '#b78b3e',
    kind: 'period',
    builtin: true,
    fields: [
      { id: 'supplier', label: 'Поставщик', type: 'text' },
      { id: 'reference', label: 'Номер заказа', type: 'text' },
    ],
  },
  {
    id: 'acceptance',
    label: 'Приёмка',
    icon: 'badge-check',
    color: '#4e9c70',
    kind: 'point',
    builtin: true,
    fields: [{ id: 'result', label: 'Результат', type: 'text' }],
  },
];

export const universalTemplates: Template[] = [
  {
    id: 'template-free',
    name: 'Свободный процесс',
    description:
      'Любой процесс с подготовкой, периодом работы и результатом. Все даты и поля можно изменить.',
    items: [
      {
        key: 'root',
        title: 'Новый процесс',
        typeId: 'process',
        kind: 'process',
        offsetDays: 0,
        durationDays: 7,
      },
      {
        key: 'prepare',
        parentKey: 'root',
        title: 'Подготовка',
        typeId: 'task',
        kind: 'period',
        offsetDays: 0,
        durationDays: 2,
      },
      {
        key: 'work',
        parentKey: 'root',
        title: 'Основной период',
        typeId: 'period',
        kind: 'period',
        offsetDays: 2,
        durationDays: 4,
      },
      {
        key: 'result',
        parentKey: 'root',
        title: 'Результат',
        typeId: 'event',
        kind: 'point',
        offsetDays: 6,
        durationDays: 0,
      },
    ],
    dependencies: [
      { fromKey: 'prepare', toKey: 'work', kind: 'finish-start', lagMinutes: 0 },
      { fromKey: 'work', toKey: 'result', kind: 'finish-start', lagMinutes: 0 },
    ],
  },
  {
    id: 'template-trip',
    name: 'Поездка',
    description:
      'Подготовка, путь, время на месте и возвращение. Даты считаются относительно начала поездки.',
    items: [
      {
        key: 'root',
        title: 'Новая поездка',
        typeId: 'trip',
        kind: 'period',
        offsetDays: 0,
        durationDays: 5,
      },
      {
        key: 'prepare',
        parentKey: 'root',
        title: 'Билеты и жильё',
        typeId: 'task',
        kind: 'period',
        offsetDays: -7,
        durationDays: 2,
      },
      {
        key: 'out',
        parentKey: 'root',
        title: 'Выезд',
        typeId: 'event',
        kind: 'point',
        offsetDays: 0,
        durationDays: 0,
      },
      {
        key: 'stay',
        parentKey: 'root',
        title: 'На месте',
        typeId: 'period',
        kind: 'period',
        offsetDays: 0,
        durationDays: 5,
      },
      {
        key: 'back',
        parentKey: 'root',
        title: 'Возвращение',
        typeId: 'event',
        kind: 'point',
        offsetDays: 5,
        durationDays: 0,
      },
    ],
    dependencies: [
      { fromKey: 'prepare', toKey: 'out', kind: 'finish-start', lagMinutes: 0 },
      { fromKey: 'stay', toKey: 'back', kind: 'finish-start', lagMinutes: 0 },
    ],
  },
  {
    id: 'template-vacation',
    name: 'Отпуск',
    description: 'Период отдыха, подготовка и первый день после возвращения.',
    items: [
      {
        key: 'root',
        title: 'Новый отпуск',
        typeId: 'vacation',
        kind: 'period',
        offsetDays: 0,
        durationDays: 14,
      },
      {
        key: 'prepare',
        parentKey: 'root',
        title: 'Подготовиться к отпуску',
        typeId: 'task',
        kind: 'period',
        offsetDays: -3,
        durationDays: 2,
      },
      {
        key: 'return',
        title: 'Вернуться к обычному ритму',
        typeId: 'event',
        kind: 'point',
        offsetDays: 14,
        durationDays: 0,
      },
    ],
    dependencies: [
      { fromKey: 'prepare', toKey: 'root', kind: 'finish-start', lagMinutes: 0 },
      { fromKey: 'root', toKey: 'return', kind: 'finish-start', lagMinutes: 0 },
    ],
  },
  {
    id: 'template-work',
    name: 'Поставка → работа → приёмка',
    description:
      'Связанный рабочий процесс. Ответственных, ресурсы и срок обязательства задайте после создания.',
    items: [
      {
        key: 'root',
        title: 'Новый рабочий процесс',
        typeId: 'process',
        kind: 'process',
        offsetDays: 0,
        durationDays: 6,
      },
      {
        key: 'delivery',
        parentKey: 'root',
        title: 'Поставка',
        typeId: 'delivery',
        kind: 'period',
        offsetDays: 0,
        durationDays: 3,
      },
      {
        key: 'work',
        parentKey: 'root',
        title: 'Выполнить работу',
        typeId: 'task',
        kind: 'period',
        offsetDays: 3,
        durationDays: 2,
      },
      {
        key: 'acceptance',
        parentKey: 'root',
        title: 'Принять результат',
        typeId: 'acceptance',
        kind: 'point',
        offsetDays: 5,
        durationDays: 0,
      },
    ],
    dependencies: [
      { fromKey: 'delivery', toKey: 'work', kind: 'finish-start', lagMinutes: 0 },
      { fromKey: 'work', toKey: 'acceptance', kind: 'finish-start', lagMinutes: 0 },
    ],
  },
];

/** Every seeded object is explicitly marked sample; no connector or person is presented as real. */
export function createSeed(now = DateTime.now().toUTC().toISO()!): PlannerSnapshot {
  const parsed = DateTime.fromISO(now, { setZone: true });
  if (!parsed.isValid) throw new Error('Некорректное время начального набора.');
  const at = parsed.toUTC().toISO()!,
    timezone = 'Asia/Yekaterinburg',
    today = parsed.setZone(timezone).startOf('day');
  const date = (days: number, hour = 9, minute = 0) => today.plus({ days }).set({ hour, minute });
  const range = (
    start: DateTime | null,
    end: DateTime | null = null,
    precision: TimeRange['precision'] = 'exact',
    zone = timezone,
  ): TimeRange => ({
    start: start?.setZone(zone).toISO() ?? null,
    end: end?.setZone(zone).toISO() ?? null,
    timezone: zone,
    precision: start ? precision : 'unknown',
  });
  const created = parsed.minus({ days: 5 }).toUTC().toISO()!;
  const entity = (
    id: string,
    workspaceId: string,
    typeId: string,
    title: string,
    plan: TimeRange,
    extra: Partial<Entity> = {},
  ): Entity => ({
    id,
    workspaceId,
    typeId,
    kind: builtinTypes.find((type) => type.id === typeId)?.kind ?? 'period',
    title,
    description: '',
    parentId: null,
    ownerId: 'local-owner',
    participantIds: [],
    status: 'planned',
    plan,
    baseline: { ...plan },
    actual: null,
    forecast: null,
    dueAt: null,
    tags: [],
    fields: {},
    links: [],
    allocations: [],
    recurrence: null,
    source: {
      kind: 'sample',
      label: 'Пример — не реальные данные',
      observedAt: at,
      receivedAt: at,
    },
    createdAt: created,
    updatedAt: at,
    version: 1,
    ...extra,
  });
  let monday = today.plus({ days: (8 - today.weekday) % 7 || 7 });
  const work = (days: number, hour = 9, minute = 0) => monday.plus({ days }).set({ hour, minute });
  const entities: Entity[] = [
    entity(
      'personal-trip',
      'personal',
      'trip',
      'Поездка в Стамбул',
      range(date(13), date(18, 20), 'day'),
      {
        description:
          'Собрать всё о поездке в одном периоде: билеты, жильё, встречи и заметки. Это пример; реальные бронирования не выполнялись.',
        tags: ['поездка', 'личное'],
        fields: { destination: 'Стамбул', budget: 85000 },
      },
    ),
    entity('personal-trip-flight', 'personal', 'event', 'Вылет', range(date(13, 8, 20)), {
      parentId: 'personal-trip',
      description: 'Пример отметки с точным временем. Проверьте свой билет.',
      fields: { airport: 'Аэропорт вылета' },
      tags: ['поездка'],
    }),
    entity(
      'personal-trip-stay',
      'personal',
      'period',
      'Время в городе',
      range(date(13, 12), date(18, 12), 'day', 'Europe/Istanbul'),
      {
        parentId: 'personal-trip',
        fields: { neighborhood: 'Галата', checkIn: 'После 14:00' },
        description: 'Вложенный период со своим часовым поясом.',
        tags: ['поездка'],
      },
    ),
    entity(
      'personal-trip-note',
      'personal',
      'note',
      'Места, куда хочется зайти',
      emptyRange(timezone),
      {
        parentId: 'personal-trip',
        status: 'draft',
        description:
          'Прогулка вдоль Босфора\nКофе в Каракёй\nДень без расписания\n\nУ заметки нет придуманной даты.',
        fields: { priority: 'Без спешки' },
      },
    ),
    entity(
      'personal-vacation',
      'personal',
      'vacation',
      'Неделя для себя',
      range(date(27, 0), date(34, 0), 'day'),
      {
        description: 'Отпуск с открытым пространством для планов. Место можно определить позже.',
        fields: { destination: 'Пока не выбрано' },
        tags: ['отдых'],
      },
    ),
    entity(
      'personal-learning',
      'personal',
      'learning',
      'Курс: визуальное мышление',
      range(date(-3, 18), date(24, 20), 'day'),
      {
        status: 'active',
        actual: range(date(-3, 18)),
        fields: { subject: 'Визуальное мышление', progress: 25 },
        tags: ['обучение'],
      },
    ),
    entity(
      'personal-learning-session',
      'personal',
      'learning',
      'Практика — 45 минут',
      range(date(1, 19), date(1, 19, 45)),
      {
        parentId: 'personal-learning',
        recurrence: { frequency: 'week', interval: 1, weekdays: [2, 4], count: 8, exceptions: [] },
        fields: { subject: 'Практика', progress: 0 },
        tags: ['обучение', 'повтор'],
      },
    ),
    entity(
      'personal-daily-walk',
      'personal',
      'period',
      'Прогулка',
      range(date(0, 18, 30), date(0, 19)),
      {
        recurrence: {
          frequency: 'day',
          interval: 1,
          count: 21,
          exceptions: [date(3).toISODate()!],
        },
        description:
          'Повтор каждый день, с одним исключением. Изменяйте правило или конкретный день.',
        tags: ['ритм', 'повтор'],
      },
    ),
    entity('personal-idea', 'personal', 'note', 'Идея на потом', emptyRange(timezone), {
      status: 'draft',
      description:
        'Сделать небольшой альбом из заметок и фотографий. Дата не нужна, пока идея не стала планом.',
      fields: { category: 'Творчество' },
    }),
    entity(
      'personal-flexible',
      'personal',
      'period',
      'Встретиться с друзьями',
      {
        ...range(date(5, 19), date(5, 21), 'approximate'),
        earliest: date(4, 18).toISO(),
        latest: date(8, 22).toISO(),
      },
      {
        description: 'Пример приблизительного периода: время нужно согласовать.',
        tags: ['примерное время'],
      },
    ),
    entity('personal-metric-1', 'personal', 'metric', 'Утренняя энергия', range(date(-2, 8)), {
      status: 'done',
      actual: range(date(-2, 8)),
      fields: { value: 7, unit: 'из 10' },
      tags: ['измерения'],
    }),
    entity('personal-metric-2', 'personal', 'metric', 'Утренняя энергия', range(date(-1, 8)), {
      status: 'done',
      actual: range(date(-1, 8)),
      fields: { value: 8, unit: 'из 10' },
      tags: ['измерения'],
    }),
    entity('personal-metric-3', 'personal', 'metric', 'Утренняя энергия', range(date(0, 8)), {
      status: 'done',
      actual: range(date(0, 8)),
      fields: { value: 6, unit: 'из 10' },
      tags: ['измерения'],
    }),
    entity(
      'team-process',
      'team',
      'process',
      'Подготовить студию к открытию',
      range(work(0), work(7, 18), 'day'),
      {
        description:
          'Пример рабочего процесса с поставкой, зависимостями, приёмкой и общим ресурсом. Все участники и сроки демонстрационные.',
        tags: ['работа', 'запуск'],
        participantIds: ['demo-coordinator', 'demo-approver'],
      },
    ),
    entity('team-agreement', 'team', 'event', 'Согласовать спецификацию', range(work(-2, 11)), {
      parentId: 'team-process',
      status: 'done',
      actual: range(work(-2, 11, 20)),
      description: 'История сохраняет принятое время отдельно от факта.',
      ownerId: 'demo-coordinator',
      fields: { version: '1.0', approved: true },
    }),
    entity(
      'team-delivery',
      'team',
      'delivery',
      'Доставка оборудования',
      range(work(0), work(2, 16)),
      {
        parentId: 'team-process',
        forecast: range(work(0), work(4, 12)),
        forecastProvenance: 'manual',
        dueAt: work(2, 16).toISO(),
        description:
          'Пример прогноза задержки: перетащите период и посмотрите влияние на монтаж и приёмку.',
        ownerId: 'demo-coordinator',
        fields: { supplier: 'Пример поставщика', reference: 'DEMO-24' },
        tags: ['работа', 'ожидает поставку'],
      },
    ),
    entity('team-install', 'team', 'task', 'Монтаж оборудования', range(work(3), work(3, 17)), {
      parentId: 'team-process',
      forecast: range(work(4, 12), work(4, 20)),
      forecastProvenance: 'derived',
      dueAt: work(3, 17).toISO(),
      ownerId: 'local-owner',
      allocations: [{ resourceId: 'team-crew', amount: 1 }],
      description: 'Одна бригада. Прогноз пересекается с другим заказом.',
      tags: ['работа'],
    }),
    entity('team-acceptance', 'team', 'acceptance', 'Приёмка студии', range(work(4, 10)), {
      parentId: 'team-process',
      forecast: range(work(7, 10)),
      forecastProvenance: 'derived',
      dueAt: work(4, 12).toISO(),
      ownerId: 'demo-approver',
      fields: { result: 'Ожидает проверки' },
      tags: ['решение'],
    }),
    entity(
      'team-other-work',
      'team',
      'task',
      'Настройка другой площадки',
      range(work(4, 13), work(4, 17)),
      {
        allocations: [{ resourceId: 'team-crew', amount: 1 }],
        ownerId: 'demo-coordinator',
        description:
          'Пример второго обязательства на ту же бригаду. Конфликт выводится из расписания, а не нарисован вручную.',
        tags: ['работа'],
      },
    ),
    entity(
      'team-overdue',
      'team',
      'task',
      'Проверить доступ на площадку',
      range(date(-2), date(-1, 17)),
      {
        parentId: 'team-process',
        dueAt: date(-1, 17).toISO(),
        description: 'Пример незавершённого обязательства, у которого прошёл срок.',
        tags: ['работа'],
      },
    ),
    entity(
      'team-inspection',
      'team',
      'inspection',
      'Проверка перед открытием',
      range(work(4, 11), work(4, 12)),
      {
        kind: 'period',
        parentId: 'team-process',
        fields: { checklist: 'Электропитание, доступ, безопасность', passed: false, issueCount: 0 },
        description:
          'Пользовательский тип с собственными полями; календарная логика остаётся общей.',
      },
    ),
    entity('team-undated', 'team', 'note', 'Обсудить второй этап', emptyRange(timezone), {
      status: 'draft',
      parentId: 'team-process',
      description: 'Контекст есть, даты пока нет. Не превращаем неизвестность в точное событие.',
    }),
  ];
  const snapshot: PlannerSnapshot = {
    user: { id: 'local-owner', displayName: 'Вы', local: true },
    users: [
      { id: 'local-owner', displayName: 'Вы', local: true },
      { id: 'demo-coordinator', displayName: 'Координатор · пример', local: true },
      { id: 'demo-approver', displayName: 'Принимающий · пример', local: true },
    ],
    memberships: [
      { workspaceId: 'personal', userId: 'local-owner', role: 'owner' },
      { workspaceId: 'team', userId: 'local-owner', role: 'owner' },
      { workspaceId: 'team', userId: 'demo-coordinator', role: 'editor' },
      { workspaceId: 'team', userId: 'demo-approver', role: 'approver' },
    ],
    workspaces: [
      {
        id: 'personal',
        name: 'Моя шкала',
        mode: 'personal',
        timezone,
        createdAt: created,
        description: 'Поездки, отдых, обучение, привычки и идеи.',
      },
      {
        id: 'team',
        name: 'Командная работа',
        mode: 'team',
        timezone,
        createdAt: created,
        description: 'Пример процесса с ответственностью и согласованиями.',
      },
    ],
    types: [
      ...builtinTypes.map((type) => ({
        ...type,
        fields: type.fields.map((field) => ({ ...field })),
      })),
      {
        id: 'inspection',
        workspaceId: 'team',
        label: 'Проверка',
        icon: 'list-checks',
        color: '#72935d',
        kind: 'period',
        fields: [
          { id: 'checklist', label: 'Что проверить', type: 'text', required: true },
          { id: 'passed', label: 'Проверка пройдена', type: 'boolean' },
          { id: 'issueCount', label: 'Замечания', type: 'number' },
        ],
      },
    ],
    entities,
    dependencies: [
      {
        id: 'dep-agreement-delivery',
        workspaceId: 'team',
        fromId: 'team-agreement',
        toId: 'team-delivery',
        kind: 'finish-start',
        lagMinutes: 0,
      },
      {
        id: 'dep-delivery-install',
        workspaceId: 'team',
        fromId: 'team-delivery',
        toId: 'team-install',
        kind: 'finish-start',
        lagMinutes: 60,
      },
      {
        id: 'dep-install-acceptance',
        workspaceId: 'team',
        fromId: 'team-install',
        toId: 'team-acceptance',
        kind: 'finish-start',
        lagMinutes: 60,
      },
      {
        id: 'dep-inspection-acceptance',
        workspaceId: 'team',
        fromId: 'team-inspection',
        toId: 'team-acceptance',
        kind: 'finish-start',
        lagMinutes: 0,
      },
      {
        id: 'dep-trip-note',
        workspaceId: 'personal',
        fromId: 'personal-trip',
        toId: 'personal-trip-note',
        kind: 'related',
        lagMinutes: 0,
      },
    ],
    resources: [
      {
        id: 'team-crew',
        workspaceId: 'team',
        name: 'Монтажная бригада · пример',
        kind: 'person',
        capacity: 1,
        unit: 'бригада',
        timezone,
        workingWeekdays: [1, 2, 3, 4, 5],
      },
    ],
    templates: structuredClone(universalTemplates),
    rules: [
      {
        id: 'rule-personal-start',
        workspaceId: 'personal',
        name: 'Скоро начинается',
        enabled: true,
        trigger: 'before-start',
        leadMinutes: 60,
        action: 'signal',
      },
      {
        id: 'rule-team-due',
        workspaceId: 'team',
        name: 'Проверить обязательство заранее',
        enabled: true,
        trigger: 'before-due',
        leadMinutes: 1440,
        action: 'signal',
      },
    ],
    signals: [],
    notifications: [],
    comments: [
      {
        id: 'comment-sample',
        workspaceId: 'team',
        entityId: 'team-delivery',
        userId: 'demo-coordinator',
        text: 'Пример обсуждения: проверим варианты нового графика до его согласования.',
        createdAt: at,
      },
    ],
    scenarios: [],
    audit: [],
    settings: {
      notifications: {
        quietStart: '22:00',
        quietEnd: '08:00',
        timezone,
        browserEnabled: false,
        repeatMinutes: 120,
        escalationMinutes: 1440,
      },
      lastSeenAt: null,
    },
    serverTime: at,
    revision: 1,
  };
  snapshot.signals = evaluateSignals(snapshot, at);
  return snapshot;
}
